# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='learned',
            field=models.BooleanField(default=False),
        ),
    ]
