# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-10 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_word_learned'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteroccurrence',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Word'),
            preserve_default=False,
        ),
    ]
