# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-13 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_characteroccurrence_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='english_translation',
        ),
    ]
